# Generated by Django 4.1.1 on 2023-01-09 21:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricMeter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Electric Meter',
                'verbose_name_plural': 'Electric Meters',
            },
        ),
        migrations.CreateModel(
            name='ElectricMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('kwh', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('electric_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.electricmeter')),
            ],
            options={
                'verbose_name': 'Electric Measure',
                'verbose_name_plural': 'Electric Measures',
            },
        ),
    ]
